Carros com consumo e outros aspectos
mpg: consumo, hp cavalos, cyl numero de cilindros, disp cilindradas
```{r}
#install.packages('corrgram')
library(corrgram)
mtcars
dim(mtcars)
```
Correlação
```{r}
cor(mtcars[1:4])
corrgram(mtcars[1:11], order=T, lower.panel = panel.shade,
         upper.panel = panel.pie, text.panel = panel.txt,
         main='Carros')
```
Analisamos cilindradas vs consumo
```{r}
plot(mtcars$mpg ~ mtcars$disp, ylab='Consumo', xlab='Cilindradas', main='Carros')
```
Modelo usando cilindradas para prever consumo
Interceptação e Inclinação
```{r}
modelo = lm(mpg ~ disp, data = mtcars)
modelo
```
Coeficiente de Determinação (71% da variavel dependente é explicada pela variavel explanatória)
R2 ajustado
```{r}
summary(modelo)$r.squared
summary(modelo)$adj.r.squared
```
```{r}
plot(mpg ~ disp, data=mtcars, ylab='Consumo', xlab='Cilindradas', main='Carros')
abline(modelo)
```
```{r}
predict(modelo,data.frame(disp = 200))
```

```{r}
modelo = lm(mpg ~ disp + hp +cyl, data=mtcars)
modelo
```

```{r}
summary(modelo)$r.squared
summary(modelo)$adj.r.squared
```

```{r}
predict(modelo, data.frame(disp =200, hp = 100, cyl=4))
```

